### ISSUE TITLE
Cron program sets hourly backups, not daily

### ISSUE THREAD

**Issue by j1elo** [MarvAmBass/docker-subversion#1]
At least per the document here:
https://help.ubuntu.com/community/CronHowto#Advanced_Crontab
(see "Special strings"), the current Cron line will launch the backup script once per hour, not once per day.

Solution is easy:
use either
0 0 \* \* \* root /usr/local/bin/svn-backuper.sh
or
@daily root /usr/local/bin/svn-backuper.sh

**Comment by MarvAmBass** [comment]
thanks, didn't notice this - it's fixed now
