### ISSUE TITLE
How do you access the repos?

### ISSUE THREAD

**Issue by Nepoxx** [MarvAmBass/docker-subversion#5]
If creating a repo is as simple as adding a directory to `/var/local/svn`, how do you do a checkout on it?

Here is what my container looks like (using `docker exec -it ... bash`)

```
root@a552085cfa83:/var/local/svn/test# pwd
/var/local/svn/test
root@a552085cfa83:/var/local/svn/test# svn info http://127.0.0.1/
svn: E175002: Unexpected HTTP status 405 'Method Not Allowed' on '/'

svn: E175002: Additional errors:
svn: E175002: PROPFIND request on '/' failed: 405 Method Not Allowed
```

**Comment by MarvAmBass** [comment]
hi Nepoxx,

the root path for svn is `/svn/` not `/`

it needs some time (max. 10 minutes) until a project gets automatically initialised. (look at the cronjob configuration)

**Comment by Nepoxx** [comment]
Thank you! Would you accept a pull request to add this to the readme?

**Comment by MarvAmBass** [comment]
sure! that would be great! Thanks for helping!
