### ISSUE TITLE
volume definition for config

### ISSUE THREAD

**Issue by nickarls** [MarvAmBass/docker-subversion#7]
The dav_svn.conf references 

AuthzSVNAccessFile /etc/**apache2**/dav_svn/dav_svn.authz and
AuthUserFile /etc/**apache2**/dav_svn/dav_svn.passwd

but the Dockerfile defines 

VOLUME ["/var/local/svn", "/var/svn-backup", "/etc/**apache**/dav_svn"]

is this intentional?

when shelling into the image you see that
/etc/apache/dav_svn is empty but in order for stuff to work(tm) you have to mount
/etc/apache2/dav_svn to the folder with the authz/passwd

the documentation speaks of

-v $DAV_SVN_CONF/:/etc/apache2/dav_svn/ \

but when used, the Dockerfile-defined /etc/apache/dav_svn results in a temporary volume.

**Comment by MarvAmBass** [comment]
thanks for the 🐛 
I'll fix it

**Comment by MarvAmBass** [comment]
fixed
